### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by wcharibo** [wcharibo/coffee_recipe_generator#2]
Traceback (most recent call last):
  File "/home/woong/coffee_recipe_generator/main.py", line 5, in <module>
    from predictResult import *
  File "/home/woong/coffee_recipe_generator/predictResult.py", line 219, in <module>
    model = torch.load(PATH + 'checkpoint.pt')  # 전체 모델을 통째로 불러옴, 클래스 선언 필수
  File "/home/woong/virtualEnv/coffee/lib/python3.10/site-packages/torch/serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "/home/woong/virtualEnv/coffee/lib/python3.10/site-packages/torch/serialization.py", line 1422, in _load
    result = unpickler.load()
  File "/home/woong/virtualEnv/coffee/lib/python3.10/site-packages/torch/serialization.py", line 1415, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'BERTClassifier' on <module '__main__' from '/home/woong/coffee_recipe_generator/main.py'>

predictResult.py 파일에서 실행할 때는 문제가 없는 데, main.py에서 import하여 사용시 해당 오류 발생

**Comment by wcharibo** [comment]
model = torch.load(PATH + 'checkpoint.pt')  # 전체 모델을 통째로 불러옴, 클래스 선언 필수
model.load_state_dict(torch.load(PATH + 'model_state.pt'))  # state_dict를 불러 온 후, 모델에 저장
이렇게 학습한 모델을 불러오고 있었는 데, 첫 번째 줄에서 error 발생했음

**Comment by wcharibo** [comment]
model = BERTClassifier(bertmodel,  dr_rate=0.5).to(device)
위와 같이 모델을 정의만 해놓고
model.load_state_dict(torch.load(PATH + 'model_state.pt')) 모델에 가중치를 부여하는 방법으로 해결

**Comment by wcharibo** [comment]
https://velog.io/@dldydrhkd/AttributeError-Cant-get-attribute-BERTClassifier-on-module-main-from-path
참고하여 작성함
